const qna = [
   {num:1,que:"¿Cuál es la forma correcta del pasado simple de 'swim'?",true:"swam",false1:"swimmed",false2:"swimed"},
{num:2,que:"¿Qué tiempo verbal se usa para acciones completadas en el pasado?",true:"Past simple",false1:"Present continuous",false2:"Future perfect"},
{num:3,que:"¿Cuál es el plural de 'mouse' (ratón)?",true:"mice",false1:"mouses",false2:"mices"},
{num:4,que:"¿Qué preposición se usa con 'arrive' para ciudades?",true:"in",false1:"on",false2:"at"},
{num:5,que:"¿Cómo se forma la pregunta en presente simple con 'he'?",true:"Does he...?",false1:"Do he...?",false2:"Is he...?"},
{num:6,que:"¿Qué significa 'look forward to'?",true:"Tener ganas de",false1:"Mirar hacia adelante",false2:"Buscar algo"},
{num:7,que:"¿Cuál es la forma en -ing de 'run'?",true:"running",false1:"runing",false2:"runnning"},
{num:8,que:"¿Qué auxiliar se usa para el futuro simple?",true:"will",false1:"do",false2:"have"},
{num:9,que:"¿Cómo se dice 'yo debería' en inglés?",true:"I should",false1:"I must",false2:"I can"},
{num:10,que:"¿Qué palabra es incontable?",true:"information",false1:"book",false2:"apple"},
{num:11,que:"¿Cuál es la forma correcta del comparativo de 'big'?",true:"bigger",false1:"more big",false2:"biggerer"},
{num:12,que:"¿Qué se usa para posesión con objetos?",true:"whose",false1:"which",false2:"what"},
{num:13,que:"¿Cómo se forma el presente perfecto?",true:"have/has + past participle",false1:"have/has + infinitive",false2:"had + past participle"},
{num:14,que:"¿Qué significa 'break down'?",true:"Averiarse",false1:"Romper abajo",false2:"Descansar"},
{num:15,que:"¿Cuál es el pasado participio de 'write'?",true:"written",false1:"wrote",false2:"writed"},
{num:16,que:"¿Qué tiempo expresa una acción en progreso ahora?",true:"Present continuous",false1:"Present simple",false2:"Past continuous"},
{num:17,que:"¿Cómo se dice 'si yo fuera' en segundo condicional?",true:"If I were",false1:"If I was",false2:"If I am"},
{num:18,que:"¿Qué preposición sigue a 'good'?",true:"at",false1:"in",false2:"on"},
{num:19,que:"¿Cuál es la forma negativa de 'they have'?",true:"They don't have",false1:"They haven't",false2:"They doesn't have"},
{num:20,que:"¿Qué significa 'though' al final de una frase?",true:"Sin embargo",false1:"Aunque",false2:"Porque"},
{num:21,que:"¿Cómo se forma el superlativo de 'interesting'?",true:"the most interesting",false1:"the interestingest",false2:"the more interesting"},
{num:22,que:"¿Qué verbo modal expresa obligación?",true:"must",false1:"can",false2:"may"},
{num:23,que:"¿Cuál es la pregunta para 'She can swim'?",true:"Can she swim?",false1:"Does she can swim?",false2:"Is she can swim?"},
{num:24,que:"¿Qué tiempo se usa con 'since'?",true:"Present perfect",false1:"Past simple",false2:"Future simple"},
{num:25,que:"¿Cómo se dice 'me gusta' en inglés?",true:"I like",false1:"I am like",false2:"I likes"},
{num:26,que:"¿Qué palabra completa 'I ___ to the cinema yesterday'?",true:"went",false1:"go",false2:"going"},
{num:27,que:"¿Cuál es la forma correcta de 'there is' en plural?",true:"there are",false1:"there is",false2:"there have"},
{num:28,que:"¿Qué significa 'get up'?",true:"Levantarse",false1:"Subir",false2:"Conseguir"},
{num:29,que:"¿Cómo se forma el pasado de 'study'?",true:"studied",false1:"studyed",false2:"studying"},
{num:30,que:"¿Qué artículo usa antes de vocales?",true:"an",false1:"a",false2:"the"},
{num:31,que:"¿Cuál es el plural de 'person'?",true:"people",false1:"persons",false2:"persones"},
{num:32,que:"¿Qué preposición se usa con 'depend'?",true:"on",false1:"in",false2:"at"},
{num:33,que:"¿Cómo se forma el futuro con 'going to'?",true:"am/is/are + going to + verb",false1:"will + going to + verb",false2:"do + going to + verb"},
{num:34,que:"¿Qué significa 'take after'?",true:"Parecerse a",false1:"Tomar después",false2:"Cuidar de"},
{num:35,que:"¿Cuál es la forma negativa de 'I am'?",true:"I'm not",false1:"I amn't",false2:"I not am"},
{num:36,que:"¿Qué tiempo verbal usa 'had + past participle'?",true:"Past perfect",false1:"Present perfect",false2:"Future perfect"},
{num:37,que:"¿Cómo se dice 'más pequeño'?",true:"smaller",false1:"more small",false2:"smallest"},
{num:38,que:"¿Qué verbo modal expresa posibilidad?",true:"might",false1:"must",false2:"should"},
{num:39,que:"¿Cuál es la pregunta para 'They have finished'?",true:"Have they finished?",false1:"Do they have finished?",false2:"Did they finished?"},
{num:40,que:"¿Qué pronombre usa para objetos?",true:"me, him, her, us, them",false1:"I, he, she, we, they",false2:"my, his, her, our, their"},
{num:41,que:"¿Cómo se forma el pasado continuo?",true:"was/were + verb-ing",false1:"did + verb-ing",false2:"had + verb-ing"},
{num:42,que:"¿Qué significa 'look up to'?",true:"Admirar",false1:"Buscar",false2:"Mirar arriba"},
{num:43,que:"¿Cuál es el participio pasado de 'eat'?",true:"eaten",false1:"ated",false2:"eated"},
{num:44,que:"¿Qué se usa para cantidades contables?",true:"many",false1:"much",false2:"a lot"},
{num:45,que:"¿Cómo se dice 'el mejor'?",true:"the best",false1:"the better",false2:"the goodest"},
{num:46,que:"¿Qué preposición se usa con 'listen'?",true:"to",false1:"at",false2:"on"},
{num:47,que:"¿Cuál es la forma correcta: 'She doesn't _____'?",true:"like",false1:"likes",false2:"liking"},
{num:48,que:"¿Qué significa 'give up'?",true:"Rendirse",false1:"Dar arriba",false2:"Entregar"},
{num:49,que:"¿Cómo se forma el presente perfecto continuo?",true:"have/has been + verb-ing",false1:"have/has + verb-ing",false2:"had been + verb-ing"},
{num:50,que:"¿Qué palabra es un adverbio de frecuencia?",true:"often",false1:"soon",false2:"already"},
   {num:51,que:"¿Cuál es la forma correcta del superlativo de 'bad'?",true:"the worst",false1:"the baddest",false2:"the worse"},
{num:52,que:"¿Qué preposición se usa con 'interested'?",true:"in",false1:"on",false2:"at"},
{num:53,que:"¿Cómo se forma el pasado de 'stop'?",true:"stopped",false1:"stoped",false2:"stoppped"},
{num:54,que:"¿Qué significa 'carry on'?",true:"Continuar",false1:"Llevar encima",false2:"Cargar"},
{num:55,que:"¿Cuál es la forma negativa de 'I will go'?",true:"I won't go",false1:"I don't will go",false2:"I will not to go"},
{num:56,que:"¿Qué tiempo verbal expresa una acción futura planeada?",true:"Present continuous",false1:"Future perfect",false2:"Past simple"},
{num:57,que:"¿Cómo se dice 'menos importante'?",true:"less important",false1:"least important",false2:"fewer important"},
{num:58,que:"¿Qué verbo modal expresa consejo?",true:"should",false1:"must",false2:"can"},
{num:59,que:"¿Cuál es la pregunta para 'He has been waiting'?",true:"Has he been waiting?",false1:"Does he have been waiting?",false2:"Is he been waiting?"},
{num:60,que:"¿Qué pronombre posesivo corresponde a 'they'?",true:"their",false1:"them",false2:"theirs"},
{num:61,que:"¿Cómo se forma el primer condicional?",true:"If + present, will + verb",false1:"If + past, would + verb",false2:"If + present, present"},
{num:62,que:"¿Qué significa 'turn down'?",true:"Rechazar",false1:"Bajar el volumen",false2:"Apagar"},
{num:63,que:"¿Cuál es el participio pasado de 'see'?",true:"seen",false1:"saw",false2:"seeed"},
{num:64,que:"¿Qué se usa para cantidades incontables?",true:"much",false1:"many",false2:"few"},
{num:65,que:"¿Cómo se dice 'el peor'?",true:"the worst",false1:"the worse",false2:"the baddest"},
{num:66,que:"¿Qué preposición se usa con 'dream'?",true:"about",false1:"on",false2:"at"},
{num:67,que:"¿Cuál es la forma correcta: 'We _____ to school every day'?",true:"go",false1:"goes",false2:"going"},
{num:68,que:"¿Qué significa 'look after'?",true:"Cuidar",false1:"Buscar",false2:"Parecerse"},
{num:69,que:"¿Cómo se forma el pasado perfecto continuo?",true:"had been + verb-ing",false1:"have been + verb-ing",false2:"was been + verb-ing"},
{num:70,que:"¿Qué palabra es un adverbio de modo?",true:"quickly",false1:"sometimes",false2:"here"},
{num:71,que:"¿Cuál es la forma correcta del comparativo de 'far'?",true:"further",false1:"farrer",false2:"more far"},
{num:72,que:"¿Qué preposición se usa con 'believe'?",true:"in",false1:"on",false2:"at"},
{num:73,que:"¿Cómo se forma el pasado de 'try'?",true:"tried",false1:"tryed",false2:"trying"},
{num:74,que:"¿Qué significa 'put off'?",true:"Posponer",false1:"Apagar",false2:"Vestirse"},
{num:75,que:"¿Cuál es la forma interrogativa de 'She would come'?",true:"Would she come?",false1:"Does she would come?",false2:"Is she would come?"},
{num:76,que:"¿Qué tiempo se usa para acciones habituales?",true:"Present simple",false1:"Present perfect",false2:"Past continuous"},
{num:77,que:"¿Cómo se dice 'tan rápido como'?",true:"as fast as",false1:"so fast as",false2:"more fast than"},
{num:78,que:"¿Qué verbo modal expresa habilidad?",true:"can",false1:"must",false2:"should"},
{num:79,que:"¿Cuál es la pregunta para 'They had left'?",true:"Had they left?",false1:"Did they had left?",false2:"Have they left?"},
{num:80,que:"¿Qué pronombre reflexivo corresponde a 'I'?",true:"myself",false1:"me",false2:"mine"},
{num:81,que:"¿Cómo se forma el segundo condicional?",true:"If + past, would + verb",false1:"If + present, will + verb",false2:"If + past, had + verb"},
{num:82,que:"¿Qué significa 'get along with'?",true:"Llevarse bien con",false1:"Salir con",false2:"Avanzar"},
{num:83,que:"¿Cuál es el participio pasado de 'take'?",true:"taken",false1:"took",false2:"taked"},
{num:84,que:"¿Qué se usa con sustantivos contables en negativo?",true:"many",false1:"much",false2:"a lot of"},
{num:85,que:"¿Cómo se dice 'más lejos'?",true:"further",false1:"farther",false2:"more far"},
{num:86,que:"¿Qué preposición se usa con 'wait'?",true:"for",false1:"to",false2:"at"},
{num:87,que:"¿Cuál es la forma correcta: 'It _____ raining now'?",true:"is",false1:"are",false2:"am"},
{num:88,que:"¿Qué significa 'run out of'?",true:"Quedarse sin",false1:"Salir corriendo",false2:"Correr fuera"},
{num:89,que:"¿Cómo se forma el futuro perfecto?",true:"will have + past participle",false1:"will be + verb-ing",false2:"will have + verb-ing"},
{num:90,que:"¿Qué palabra es un conector de contraste?",true:"however",false1:"therefore",false2:"moreover"},
{num:91,que:"¿Cuál es la forma correcta del plural de 'knife'?",true:"knives",false1:"knifes",false2:"knive"},
{num:92,que:"¿Qué preposición se usa con 'succeed'?",true:"in",false1:"on",false2:"at"},
{num:93,que:"¿Cómo se forma el pasado de 'plan'?",true:"planned",false1:"planed",false2:"planning"},
{num:94,que:"¿Qué significa 'call off'?",true:"Cancelar",false1:"Llamar",false2:"Apagar"},
{num:95,que:"¿Cuál es la forma negativa de 'You must go'?",true:"You mustn't go",false1:"You don't must go",false2:"You must not to go"},
{num:96,que:"¿Qué tiempo expresa una acción que ocurrió antes de otra en el pasado?",true:"Past perfect",false1:"Past simple",false2:"Present perfect"},
{num:97,que:"¿Cómo se dice 'mejor que'?",true:"better than",false1:"more good than",false2:"gooder than"},
{num:98,que:"¿Qué verbo modal expresa permiso?",true:"may",false1:"must",false2:"should"},
{num:99,que:"¿Cuál es la pregunta para 'I had been studying'?",true:"Had you been studying?",false1:"Did you had been studying?",false2:"Have you been studying?"},
{num:100,que:"¿Qué pronombre objeto corresponde a 'she'?",true:"her",false1:"hers",false2:"she"},
{num:101,que:"¿Cómo se forma el tercer condicional?",true:"If + past perfect, would have + past participle",false1:"If + past, would + verb",false2:"If + present, will have + verb"},
{num:102,que:"¿Qué significa 'bring up'?",true:"Criar/Educar",false1:"Traer arriba",false2:"Levantar"},
{num:103,que:"¿Cuál es el participio pasado de 'drive'?",true:"driven",false1:"drove",false2:"drived"},
{num:104,que:"¿Qué se usa en preguntas con sustantivos contables?",true:"many",false1:"much",false2:"a lot"},
{num:105,que:"¿Cómo se dice 'el menos inteligente'?",true:"the least intelligent",false1:"the less intelligent",false2:"the intelligentest"},
{num:106,que:"¿Qué preposición se usa con 'apologize'?",true:"for",false1:"to",false2:"at"},
{num:107,que:"¿Cuál es la forma correcta: 'They _____ never been here'?",true:"have",false1:"has",false2:"had"},
{num:108,que:"¿Qué significa 'set up'?",true:"Establecer",false1:"Sentarse",false2:"Poner arriba"},
{num:109,que:"¿Cómo se forma el futuro continuo?",true:"will be + verb-ing",false1:"will have + verb-ing",false2:"will + verb-ing"},
{num:110,que:"¿Qué palabra es un conector de causa?",true:"because",false1:"however",false2:"furthermore"},
{num:111,que:"¿Cuál es la forma correcta del plural de 'wife'?",true:"wives",false1:"wifes",false2:"wive"},
{num:112,que:"¿Qué preposición se usa con 'concentrate'?",true:"on",false1:"in",false2:"at"},
{num:113,que:"¿Cómo se forma el pasado de 'refer'?",true:"referred",false1:"refered",false2:"referring"},
{num:114,que:"¿Qué significa 'give in'?",true:"Rendirse",false1:"Entregar",false2:"Dar dentro"},
{num:115,que:"¿Cuál es la forma interrogativa de 'We can help'?",true:"Can we help?",false1:"Do we can help?",false2:"Are we can help?"},
{num:116,que:"¿Qué tiempo se usa con 'for' + periodo de tiempo?",true:"Present perfect",false1:"Past simple",false2:"Future simple"},
{num:117,que:"¿Cómo se dice 'tan inteligente como'?",true:"as intelligent as",false1:"so intelligent as",false2:"more intelligent than"},
{num:118,que:"¿Qué verbo modal expresa prohibición?",true:"mustn't",false1:"can't",false2:"shouldn't"},
{num:119,que:"¿Cuál es la pregunta para 'She will have finished'?",true:"Will she have finished?",false1:"Does she will have finished?",false2:"Is she will have finished?"},
{num:120,que:"¿Qué pronombre reflexivo corresponde a 'you' (singular)?",true:"yourself",false1:"yours",false2:"you"},
{num:121,que:"¿Cómo se forma el condicional cero?",true:"If + present, present",false1:"If + past, would + verb",false2:"If + present, will + verb"},
{num:122,que:"¿Qué significa 'find out'?",true:"Descubrir",false1:"Buscar",false2:"Encontrar"},
{num:123,que:"¿Cuál es el participio pasado de 'break'?",true:"broken",false1:"broke",false2:"breaked"},
{num:124,que:"¿Qué se usa en oraciones afirmativas con sustantivos incontables?",true:"a lot of",false1:"many",false2:"few"},
{num:125,que:"¿Cómo se dice 'peor que'?",true:"worse than",false1:"more bad than",false2:"badder than"},
{num:126,que:"¿Qué preposición se usa con 'rely'?",true:"on",false1:"in",false2:"at"},
{num:127,que:"¿Cuál es la forma correcta: 'He _____ not like coffee'?",true:"does",false1:"do",false2:"is"},
{num:128,que:"¿Qué significa 'take off'?",true:"Despegar",false1:"Quitarse",false2:"Tomar fuera"},
{num:129,que:"¿Cómo se forma el pasado perfecto?",true:"had + past participle",false1:"have + past participle",false2:"was + past participle"},
{num:130,que:"¿Qué palabra es un conector de secuencia?",true:"then",false1:"but",false2:"because"},
{num:131,que:"¿Cuál es la forma correcta del plural de 'child'?",true:"children",false1:"childs",false2:"childes"},
{num:132,que:"¿Qué preposición se usa con 'accuse'?",true:"of",false1:"for",false2:"with"},
{num:133,que:"¿Cómo se forma el pasado de 'occur'?",true:"occurred",false1:"occured",false2:"occurring"},
{num:134,que:"¿Qué significa 'look into'?",true:"Investigar",false1:"Mirar dentro",false2:"Buscar"},
{num:135,que:"¿Cuál es la forma negativa de 'They might come'?",true:"They might not come",false1:"They don't might come",false2:"They might not to come"},
{num:136,que:"¿Qué tiempo expresa una acción futura en progreso?",true:"Future continuous",false1:"Future perfect",false2:"Present continuous"},
{num:137,que:"¿Cómo se dice 'el más alto'?",true:"the tallest",false1:"the taller",false2:"the most tall"},
{num:138,que:"¿Qué verbo modal expresa deducción?",true:"must",false1:"can",false2:"should"},
{num:139,que:"¿Cuál es la pregunta para 'We used to live here'?",true:"Did we use to live here?",false1:"Used we to live here?",false2:"Do we used to live here?"},
{num:140,que:"¿Qué pronombre posesivo corresponde a 'it'?",true:"its",false1:"it's",false2:"it"},
{num:141,que:"¿Cómo se forma la voz pasiva en presente simple?",true:"am/is/are + past participle",false1:"was/were + past participle",false2:"have/has + past participle"},
{num:142,que:"¿Qué significa 'go on'?",true:"Continuar",false1:"Ir encima",false2:"Suceder"},
{num:143,que:"¿Cuál es el participio pasado de 'choose'?",true:"chosen",false1:"chose",false2:"choosed"},
{num:144,que:"¿Qué se usa en oraciones negativas con sustantivos incontables?",true:"much",false1:"many",false2:"a few"},
{num:145,que:"¿Cómo se dice 'menos popular que'?",true:"less popular than",false1:"least popular than",false2:"fewer popular than"},
{num:146,que:"¿Qué preposición se usa con 'belong'?",true:"to",false1:"with",false2:"for"},
{num:147,que:"¿Cuál es la forma correcta: 'I _____ already eaten'?",true:"have",false1:"has",false2:"had"},
{num:148,que:"¿Qué significa 'turn up'?",true:"Aparecer",false1:"Subir el volumen",false2:"Apagar"},
{num:149,que:"¿Cómo se forma el futuro con 'shall'?",true:"shall + verb",false1:"shall to + verb",false2:"shall + verb-ing"},
{num:150,que:"¿Qué palabra es un conector de resultado?",true:"so",false1:"but",false2:"although"},
   {num:151,que:"¿Cuál es la forma correcta del plural de 'tooth'?",true:"teeth",false1:"tooths",false2:"toothes"},
{num:152,que:"¿Qué preposición se usa con 'complain'?",true:"about",false1:"on",false2:"at"},
{num:153,que:"¿Cómo se forma el pasado de 'prefer'?",true:"preferred",false1:"prefered",false2:"preferring"},
{num:154,que:"¿Qué significa 'pass away'?",true:"Fallecer",false1:"Pasar lejos",false2:"Aprobar"},
{num:155,que:"¿Cuál es la forma negativa de 'She ought to come'?",true:"She ought not to come",false1:"She doesn't ought to come",false2:"She ought not come"},
{num:156,que:"¿Qué tiempo se usa en reported speech para cambios de presente a pasado?",true:"Past simple",false1:"Present perfect",false2:"Future simple"},
{num:157,que:"¿Cómo se dice 'tan bueno como'?",true:"as good as",false1:"so good as",false2:"better than"},
{num:158,que:"¿Qué verbo modal expresa posibilidad en el pasado?",true:"could have",false1:"should have",false2:"must have"},
{num:159,que:"¿Cuál es la pregunta para 'They would have come'?",true:"Would they have come?",false1:"Did they would have come?",false2:"Have they would come?"},
{num:160,que:"¿Qué pronombre reflexivo corresponde a 'we'?",true:"ourselves",false1:"ourself",false2:"us"},
{num:161,que:"¿Cómo se forma el reported speech de 'I am tired'?",true:"He said he was tired",false1:"He said he is tired",false2:"He said he were tired"},
{num:162,que:"¿Qué significa 'stand up for'?",true:"Defender",false1:"Levantarse",false2:"Soportar"},
{num:163,que:"¿Cuál es el participio pasado de 'forget'?",true:"forgotten",false1:"forgot",false2:"forgetted"},
{num:164,que:"¿Qué se usa con 'there is' para sustantivos incontables?",true:"some",false1:"any",false2:"many"},
{num:165,que:"¿Cómo se dice 'el más divertido'?",true:"the funniest",false1:"the funnier",false2:"the most funny"},
{num:166,que:"¿Qué preposición se usa con 'insist'?",true:"on",false1:"in",false2:"at"},
{num:167,que:"¿Cuál es la forma correcta: 'Neither John nor Mary _____ coming'?",true:"is",false1:"are",false2:"be"},
{num:168,que:"¿Qué significa 'bring about'?",true:"Causar",false1:"Traer alrededor",false2:"Llevar"},
{num:169,que:"¿Cómo se forma el futuro perfecto continuo?",true:"will have been + verb-ing",false1:"will be having + verb-ing",false2:"will have being + verb-ing"},
{num:170,que:"¿Qué palabra es un conector de propósito?",true:"in order to",false1:"however",false2:"therefore"},
{num:171,que:"¿Cuál es la forma correcta del plural de 'foot'?",true:"feet",false1:"foots",false2:"feets"},
{num:172,que:"¿Qué preposición se usa con 'approve'?",true:"of",false1:"with",false2:"for"},
{num:173,que:"¿Cómo se forma el pasado de 'admit'?",true:"admitted",false1:"admited",false2:"admitting"},
{num:174,que:"¿Qué significa 'put up with'?",true:"Tolerar",false1:"Poner arriba con",false2:"Alojar"},
{num:175,que:"¿Cuál es la forma interrogativa de 'You had better leave'?",true:"Had you better leave?",false1:"Do you had better leave?",false2:"Have you better leave?"},
{num:176,que:"¿Qué tiempo se usa en 'wish' para deseos presentes?",true:"Past simple",false1:"Present simple",false2:"Future simple"},
{num:177,que:"¿Cómo se dice 'menos difícil que'?",true:"less difficult than",false1:"least difficult than",false2:"fewer difficult than"},
{num:178,que:"¿Qué verbo modal expresa obligación en el pasado?",true:"had to",false1:"must",false2:"should"},
{num:179,que:"¿Cuál es la pregunta para 'It must be true'?",true:"Must it be true?",false1:"Does it must be true?",false2:"Is it must be true?"},
{num:180,que:"¿Qué pronombre reflexivo corresponde a 'they'?",true:"themselves",false1:"themself",false2:"theirselves"},
{num:181,que:"¿Cómo se forma el reported speech de 'I will help'?",true:"He said he would help",false1:"He said he will help",false2:"He said he helps"},
{num:182,que:"¿Qué significa 'come across'?",true:"Encontrarse con",false1:"Venir a través",false2:"Aparecer"},
{num:183,que:"¿Cuál es el participio pasado de 'speak'?",true:"spoken",false1:"spoke",false2:"speaked"},
{num:184,que:"¿Qué se usa en preguntas ofreciendo algo?",true:"some",false1:"any",false2:"many"},
{num:185,que:"¿Cómo se dice 'el menos interesante'?",true:"the least interesting",false1:"the less interesting",false2:"the uninterestingest"},
{num:186,que:"¿Qué preposición se usa con 'consist'?",true:"of",false1:"in",false2:"on"},
{num:187,que:"¿Cuál es la forma correcta: 'Each student _____ a book'?",true:"has",false1:"have",false2:"having"},
{num:188,que:"¿Qué significa 'get over'?",true:"Superar",false1:"Llegar sobre",false2:"Conseguir"},
{num:189,que:"¿Cómo se forma el condicional mixto?",true:"If + past perfect, would + verb",false1:"If + past, would have + verb",false2:"If + present, will + verb"},
{num:190,que:"¿Qué palabra es un conector de adición?",true:"moreover",false1:"however",false2:"therefore"},
{num:191,que:"¿Cuál es la forma correcta del plural de 'man'?",true:"men",false1:"mans",false2:"mens"},
{num:192,que:"¿Qué preposición se usa con 'participate'?",true:"in",false1:"on",false2:"at"},
{num:193,que:"¿Cómo se forma el pasado de 'commit'?",true:"committed",false1:"commited",false2:"committing"},
{num:194,que:"¿Qué significa 'look down on'?",true:"Menospreciar",false1:"Mirar abajo",false2:"Buscar"},
{num:195,que:"¿Cuál es la forma negativa de 'You need to go'?",true:"You don't need to go",false1:"You needn't go",false2:"You need not to go"},
{num:196,que:"¿Qué tiempo se usa después de 'I hope'?",true:"Present simple",false1:"Past simple",false2:"Future simple"},
{num:197,que:"¿Cómo se dice 'tan difícil como'?",true:"as difficult as",false1:"so difficult as",false2:"more difficult than"},
{num:198,que:"¿Qué verbo modal expresa probabilidad?",true:"should",false1:"must",false2:"can"},
{num:199,que:"¿Cuál es la pregunta para 'She used to smoke'?",true:"Did she use to smoke?",false1:"Used she to smoke?",false2:"Does she used to smoke?"},
{num:200,que:"¿Qué pronombre objeto corresponde a 'we'?",true:"us",false1:"our",false2:"ours"},
{num:201,que:"¿Cómo se forma la voz pasiva en pasado simple?",true:"was/were + past participle",false1:"had been + past participle",false2:"have been + past participle"},
{num:202,que:"¿Qué significa 'turn into'?",true:"Convertirse en",false1:"Girar dentro",false2:"Cambiar"},
{num:203,que:"¿Cuál es el participio pasado de 'wear'?",true:"worn",false1:"wore",false2:"weared"},
{num:204,que:"¿Qué se usa con 'there are' para sustantivos contables?",true:"some",false1:"any",false2:"much"},
{num:205,que:"¿Cómo se dice 'más peligroso que'?",true:"more dangerous than",false1:"dangerouser than",false2:"most dangerous than"},
{num:206,que:"¿Qué preposición se usa con 'object'?",true:"to",false1:"with",false2:"for"},
{num:207,que:"¿Cuál es la forma correcta: 'The team _____ playing well'?",true:"is",false1:"are",false2:"be"},
{num:208,que:"¿Qué significa 'break into'?",true:"Forzar la entrada",false1:"Romper dentro",false2:"Interrumpir"},
{num:209,que:"¿Cómo se forma el presente perfecto en voz pasiva?",true:"have/has been + past participle",false1:"had been + past participle",false2:"was been + past participle"},
{num:210,que:"¿Qué palabra es un conector de tiempo?",true:"while",false1:"because",false2:"so"},
{num:211,que:"¿Cuál es la forma correcta del plural de 'woman'?",true:"women",false1:"womans",false2:"womens"},
{num:212,que:"¿Qué preposición se usa con 'suffer'?",true:"from",false1:"with",false2:"of"},
{num:213,que:"¿Cómo se forma el pasado de 'control'?",true:"controlled",false1:"controled",false2:"controlling"},
{num:214,que:"¿Qué significa 'call for'?",true:"Exigir",false1:"Llamar para",false2:"Visitar"},
{num:215,que:"¿Cuál es la forma interrogativa de 'They dare not speak'?",true:"Dare they not speak?",false1:"Do they dare not speak?",false2:"Are they dare not speak?"},
{num:216,que:"¿Qué tiempo se usa después de 'It's time'?",true:"Past simple",false1:"Present simple",false2:"Future simple"},
{num:217,que:"¿Cómo se dice 'el más hermoso'?",true:"the most beautiful",false1:"the beautifulest",false2:"the more beautiful"},
{num:218,que:"¿Qué verbo modal expresa arrepentimiento?",true:"should have",false1:"could have",false2:"must have"},
{num:219,que:"¿Cuál es la pregunta para 'We had to wait'?",true:"Did we have to wait?",false1:"Had we to wait?",false2:"Have we to wait?"},
{num:220,que:"¿Qué pronombre reflexivo corresponde a 'he'?",true:"himself",false1:"hisself",false2:"his"},
{num:221,que:"¿Cómo se forma el reported speech de 'I can swim'?",true:"He said he could swim",false1:"He said he can swim",false2:"He said he can swam"},
{num:222,que:"¿Qué significa 'do away with'?",true:"Eliminar",false1:"Hacer lejos con",false2:"Terminar"},
{num:223,que:"¿Cuál es el participio pasado de 'tear'?",true:"torn",false1:"tore",false2:"teared"},
{num:224,que:"¿Qué se usa en oraciones condicionales reales?",true:"Present simple",false1:"Past simple",false2:"Future simple"},
{num:225,que:"¿Cómo se dice 'menos importante que'?",true:"less important than",false1:"least important than",false2:"fewer important than"},
{num:226,que:"¿Qué preposición se usa con 'blame'?",true:"for",false1:"on",false2:"at"},
{num:227,que:"¿Cuál es la forma correcta: 'Either you or I _____ wrong'?",true:"am",false1:"are",false2:"is"},
{num:228,que:"¿Qué significa 'hold up'?",true:"Retrasar",false1:"Sostener",false2:"Mantener"},
{num:229,que:"¿Cómo se forma el pasado perfecto en voz pasiva?",true:"had been + past participle",false1:"have been + past participle",false2:"was been + past participle"},
{num:230,que:"¿Qué palabra es un conector de condición?",true:"if",false1:"when",false2:"because"},
{num:231,que:"¿Cuál es la forma correcta del plural de 'ox'?",true:"oxen",false1:"oxes",false2:"oxs"},
{num:232,que:"¿Qué preposición se usa con 'invest'?",true:"in",false1:"on",false2:"at"},
{num:233,que:"¿Cómo se forma el pasado de 'permit'?",true:"permitted",false1:"permited",false2:"permitting"},
{num:234,que:"¿Qué significa 'look forward to'?",true:"Esperar con ilusión",false1:"Mirar adelante",false2:"Anticipar"},
{num:235,que:"¿Cuál es la forma negativa de 'We used to live here'?",true:"We didn't use to live here",false1:"We used not to live here",false2:"We don't used to live here"},
{num:236,que:"¿Qué tiempo se usa en 'I wish' para deseos pasados?",true:"Past perfect",false1:"Past simple",false2:"Present perfect"},
{num:237,que:"¿Cómo se dice 'tan rápido como'?",true:"as fast as",false1:"so fast as",false2:"more fast than"},
{num:238,que:"¿Qué verbo modal expresa capacidad en el pasado?",true:"could",false1:"can",false2:"might"},
{num:239,que:"¿Cuál es la pregunta para 'You had been waiting'?",true:"Had you been waiting?",false1:"Did you had been waiting?",false2:"Have you been waiting?"},
{num:240,que:"¿Qué pronombre reflexivo corresponde a 'you' (plural)?",true:"yourselves",false1:"yourself",false2:"you"},
{num:241,que:"¿Cómo se forma el reported speech de 'I have finished'?",true:"He said he had finished",false1:"He said he has finished",false2:"He said he finished"},
{num:242,que:"¿Qué significa 'run into'?",true:"Encontrarse por casualidad",false1:"Correr dentro",false2:"Chocar"},
{num:243,que:"¿Cuál es el participio pasado de 'shake'?",true:"shaken",false1:"shook",false2:"shaked"},
{num:244,que:"¿Qué se usa en oraciones con 'hardly'?",true:"any",false1:"some",false2:"many"},
{num:245,que:"¿Cómo se dice 'el más valioso'?",true:"the most valuable",false1:"the valuablest",false2:"the more valuable"},
{num:246,que:"¿Qué preposición se usa con 'congratulate'?",true:"on",false1:"for",false2:"with"},
{num:247,que:"¿Cuál es la forma correcta: 'Nobody _____ the answer'?",true:"knows",false1:"know",false2:"knowing"},
{num:248,que:"¿Qué significa 'take on'?",true:"Contratar",false1:"Tomar encima",false2:"Aceptar"},
{num:249,que:"¿Cómo se forma el futuro en voz pasiva?",true:"will be + past participle",false1:"will have been + past participle",false2:"will being + past participle"},
{num:250,que:"¿Qué palabra es un conector de contraste fuerte?",true:"although",false1:"and",false2:"so"},
   {num:251,que:"¿Cuál es la forma correcta del plural de 'cactus'?",true:"cacti",false1:"cactuses",false2:"cactos"},
{num:252,que:"¿Qué preposición se usa con 'depend'?",true:"on",false1:"in",false2:"at"},
{num:253,que:"¿Cómo se forma el pasado de 'travel'?",true:"travelled",false1:"traveled",false2:"travelling"},
{num:254,que:"¿Qué significa 'pull through'?",true:"Salir adelante",false1:"Jalar a través",false2:"Empujar"},
{num:255,que:"¿Cuál es la forma negativa de 'I used to smoke'?",true:"I didn't use to smoke",false1:"I used not to smoke",false2:"I don't used to smoke"},
{num:256,que:"¿Qué tiempo se usa después de 'as soon as'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:257,que:"¿Cómo se dice 'más sabio que'?",true:"wiser than",false1:"more wise than",false2:"wisest than"},
{num:258,que:"¿Qué verbo modal expresa posibilidad remota?",true:"might",false1:"must",false2:"should"},
{num:259,que:"¿Cuál es la pregunta para 'He needn't come'?",true:"Need he come?",false1:"Does he need come?",false2:"Is he need come?"},
{num:260,que:"¿Qué pronombre corresponde a 'everyone'?",true:"they",false1:"he",false2:"it"},
{num:261,que:"¿Cómo se forma el reported speech de 'I must go'?",true:"He said he had to go",false1:"He said he must go",false2:"He said he must went"},
{num:262,que:"¿Qué significa 'fall out'?",true:"Pelearse",false1:"Caerse fuera",false2:"Desmayarse"},
{num:263,que:"¿Cuál es el participio pasado de 'steal'?",true:"stolen",false1:"stole",false2:"stealed"},
{num:264,que:"¿Qué se usa con 'there was'?",true:"singular noun",false1:"plural noun",false2:"uncountable noun"},
{num:265,que:"¿Cómo se dice 'el más antiguo'?",true:"the oldest",false1:"the elder",false2:"the most old"},
{num:266,que:"¿Qué preposición se usa con 'recover'?",true:"from",false1:"of",false2:"with"},
{num:267,que:"¿Cuál es la forma correcta: 'The police _____ investigating'?",true:"are",false1:"is",false2:"be"},
{num:268,que:"¿Qué significa 'point out'?",true:"Señalar",false1:"Apuntar fuera",false2:"Indicar"},
{num:269,que:"¿Cómo se forma el condicional con 'unless'?",true:"Unless + present",false1:"Unless + past",false2:"Unless + future"},
{num:270,que:"¿Qué palabra es un conector de ejemplificación?",true:"for example",false1:"however",false2:"therefore"},
{num:271,que:"¿Cuál es la forma correcta del plural de 'analysis'?",true:"analyses",false1:"analysises",false2:"analysises"},
{num:272,que:"¿Qué preposición se usa con 'excel'?",true:"at",false1:"in",false2:"on"},
{num:273,que:"¿Cómo se forma el pasado de 'label'?",true:"labelled",false1:"labeled",false2:"labeling"},
{num:274,que:"¿Qué significa 'wear out'?",true:"Gastar",false1:"Usar fuera",false2:"Cansar"},
{num:275,que:"¿Cuál es la forma interrogativa de 'You'd rather stay'?",true:"Would you rather stay?",false1:"Do you rather stay?",false2:"Had you rather stay?"},
{num:276,que:"¿Qué tiempo se usa después de 'by the time'?",true:"Present perfect",false1:"Past perfect",false2:"Future simple"},
{num:277,que:"¿Cómo se dice 'tan feliz como'?",true:"as happy as",false1:"so happy as",false2:"more happy than"},
{num:278,que:"¿Qué verbo modal expresa certeza en el pasado?",true:"must have",false1:"should have",false2:"could have"},
{num:279,que:"¿Cuál es la pregunta para 'They might have seen'?",true:"Might they have seen?",false1:"Did they might have seen?",false2:"Have they might seen?"},
{num:280,que:"¿Qué pronombre corresponde a 'someone'?",true:"they",false1:"he",false2:"it"},
{num:281,que:"¿Cómo se forma el reported speech de 'I may come'?",true:"He said he might come",false1:"He said he may come",false2:"He said he can come"},
{num:282,que:"¿Qué significa 'break up'?",true:"Terminar una relación",false1:"Romper arriba",false2:"Separar"},
{num:283,que:"¿Cuál es el participio pasado de 'freeze'?",true:"frozen",false1:"froze",false2:"freezed"},
{num:284,que:"¿Qué se usa con 'there were'?",true:"plural noun",false1:"singular noun",false2:"uncountable noun"},
{num:285,que:"¿Cómo se dice 'el más joven'?",true:"the youngest",false1:"the younger",false2:"the most young"},
{num:286,que:"¿Qué preposición se usa con 'protect'?",true:"from",false1:"of",false2:"with"},
{num:287,que:"¿Cuál es la forma correcta: 'Mathematics _____ difficult'?",true:"is",false1:"are",false2:"be"},
{num:288,que:"¿Qué significa 'look up'?",true:"Buscar información",false1:"Mirar arriba",false2:"Mejorar"},
{num:289,que:"¿Cómo se forma el futuro con 'be about to'?",true:"am/is/are about to + verb",false1:"will about to + verb",false2:"going to about to + verb"},
{num:290,que:"¿Qué palabra es un conector de resumen?",true:"in conclusion",false1:"for instance",false2:"however"},
{num:291,que:"¿Cuál es la forma correcta del plural de 'crisis'?",true:"crises",false1:"crisises",false2:"crisises"},
{num:292,que:"¿Qué preposición se usa con 'specialize'?",true:"in",false1:"on",false2:"at"},
{num:293,que:"¿Cómo se forma el pasado de 'signal'?",true:"signalled",false1:"signaled",false2:"signaling"},
{num:294,que:"¿Qué significa 'turn out'?",true:"Resultar ser",false1:"Apagar",false2:"Salir"},
{num:295,que:"¿Cuál es la forma negativa de 'You'd better go'?",true:"You'd better not go",false1:"You hadn't better go",false2:"You don't better go"},
{num:296,que:"¿Qué tiempo se usa después de 'while'?",true:"Past continuous",false1:"Past simple",false2:"Present perfect"},
{num:297,que:"¿Cómo se dice 'menos complicado que'?",true:"less complicated than",false1:"least complicated than",false2:"fewer complicated than"},
{num:298,que:"¿Qué verbo modal expresa ofrecimiento?",true:"shall",false1:"will",false2:"can"},
{num:299,que:"¿Cuál es la pregunta para 'She would rather leave'?",true:"Would she rather leave?",false1:"Does she rather leave?",false2:"Is she rather leave?"},
{num:300,que:"¿Qué pronombre corresponde a 'anybody'?",true:"they",false1:"he",false2:"it"},
{num:301,que:"¿Cómo se forma el reported speech de 'I shall help'?",true:"He said he would help",false1:"He said he should help",false2:"He said he shall help"},
{num:302,que:"¿Qué significa 'give away'?",true:"Regalar",false1:"Dar lejos",false2:"Rendirse"},
{num:303,que:"¿Cuál es el participio pasado de 'wake'?",true:"woken",false1:"woke",false2:"waked"},
{num:304,que:"¿Qué se usa con 'there has been'?",true:"singular noun",false1:"plural noun",false2:"countable noun"},
{num:305,que:"¿Cómo se dice 'más claro que'?",true:"clearer than",false1:"more clear than",false2:"clearest than"},
{num:306,que:"¿Qué preposición se usa con 'subscribe'?",true:"to",false1:"for",false2:"on"},
{num:307,que:"¿Cuál es la forma correcta: 'The news _____ surprising'?",true:"is",false1:"are",false2:"be"},
{num:308,que:"¿Qué significa 'hold on'?",true:"Esperar",false1:"Sostener",false2:"Mantener"},
{num:309,que:"¿Cómo se forma el condicional con 'provided that'?",true:"Provided that + present",false1:"Provided that + past",false2:"Provided that + future"},
{num:310,que:"¿Qué palabra es un conector de consecuencia?",true:"as a result",false1:"for example",false2:"in addition"},
{num:311,que:"¿Cuál es la forma correcta del plural de 'phenomenon'?",true:"phenomena",false1:"phenomenons",false2:"phenomenas"},
{num:312,que:"¿Qué preposición se usa con 'accustom'?",true:"to",false1:"with",false2:"for"},
{num:313,que:"¿Cómo se forma el pasado de 'cancel'?",true:"cancelled",false1:"canceled",false2:"canceling"},
{num:314,que:"¿Qué significa 'show up'?",true:"Aparecer",false1:"Mostrar arriba",false2:"Demostrar"},
{num:315,que:"¿Cuál es la forma interrogativa de 'We needn't wait'?",true:"Need we wait?",false1:"Do we need wait?",false2:"Are we need wait?"},
{num:316,que:"¿Qué tiempo se usa después de 'until'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:317,que:"¿Cómo se dice 'tan seguro como'?",true:"as sure as",false1:"so sure as",false2:"more sure than"},
{num:318,que:"¿Qué verbo modal expresa sugerencia?",true:"could",false1:"must",false2:"should"},
{num:319,que:"¿Cuál es la pregunta para 'He ought to know'?",true:"Ought he to know?",false1:"Does he ought to know?",false2:"Is he ought to know?"},
{num:320,que:"¿Qué pronombre corresponde a 'nobody'?",true:"they",false1:"he",false2:"it"},
{num:321,que:"¿Cómo se forma el reported speech de 'I would come'?",true:"He said he would come",false1:"He said he will come",false2:"He said he comes"},
{num:322,que:"¿Qué significa 'put forward'?",true:"Proponer",false1:"Poner adelante",false2:"Presentar"},
{num:323,que:"¿Cuál es el participio pasado de 'weave'?",true:"woven",false1:"weaved",false2:"wove"},
{num:324,que:"¿Qué se usa con 'there have been'?",true:"plural noun",false1:"singular noun",false2:"uncountable noun"},
{num:325,que:"¿Cómo se dice 'el más brillante'?",true:"the brightest",false1:"the brighter",false2:"the most bright"},
{num:326,que:"¿Qué preposición se usa con 'disapprove'?",true:"of",false1:"with",false2:"for"},
{num:327,que:"¿Cuál es la forma correcta: 'The committee _____ decided'?",true:"has",false1:"have",false2:"had"},
{num:328,que:"¿Qué significa 'take over'?",true:"Tomar el control",false1:"Tomar encima",false2:"Asumir"},
{num:329,que:"¿Cómo se forma el futuro con 'be to'?",true:"am/is/are to + verb",false1:"will to + verb",false2:"going to to + verb"},
{num:330,que:"¿Qué palabra es un conector de tiempo pasado?",true:"previously",false1:"consequently",false2:"furthermore"},
{num:331,que:"¿Cuál es la forma correcta del plural de 'thesis'?",true:"theses",false1:"thesises",false2:"thesis"},
{num:332,que:"¿Qué preposición se usa con 'hint'?",true:"at",false1:"on",false2:"for"},
{num:333,que:"¿Cómo se forma el pasado de 'compel'?",true:"compelled",false1:"compeled",false2:"compelling"},
{num:334,que:"¿Qué significa 'lay off'?",true:"Despedir",false1:"Acostarse",false2:"Dejar"},
{num:335,que:"¿Cuál es la forma negativa de 'They dare say'?",true:"They dare not say",false1:"They don't dare say",false2:"They dare not to say"},
{num:336,que:"¿Qué tiempo se usa después de 'before'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:337,que:"¿Cómo se dice 'más oscuro que'?",true:"darker than",false1:"more dark than",false2:"darkest than"},
{num:338,que:"¿Qué verbo modal expresa expectativa?",true:"should",false1:"must",false2:"can"},
{num:339,que:"¿Cuál es la pregunta para 'You had to pay'?",true:"Did you have to pay?",false1:"Had you to pay?",false2:"Have you to pay?"},
{num:340,que:"¿Qué pronombre corresponde a 'everybody'?",true:"they",false1:"he",false2:"it"},
{num:341,que:"¿Cómo se forma el reported speech de 'I might go'?",true:"He said he might go",false1:"He said he may go",false2:"He said he can go"},
{num:342,que:"¿Qué significa 'bring about'?",true:"Causar",false1:"Traer alrededor",false2:"Producir"},
{num:343,que:"¿Cuál es el participio pasado de 'strive'?",true:"striven",false1:"strove",false2:"strived"},
{num:344,que:"¿Qué se usa con 'there hadn't been'?",true:"singular noun",false1:"plural noun",false2:"any noun"},
{num:345,que:"¿Cómo se dice 'el más humilde'?",true:"the humblest",false1:"the humbler",false2:"the most humble"},
{num:346,que:"¿Qué preposición se usa con 'abstain'?",true:"from",false1:"of",false2:"with"},
{num:347,que:"¿Cuál es la forma correcta: 'The staff _____ working'?",true:"are",false1:"is",false2:"be"},
{num:348,que:"¿Qué significa 'come up with'?",true:"Proponer una idea",false1:"Venir con",false2:"Aparecer"},
{num:349,que:"¿Cómo se forma el condicional con 'as long as'?",true:"As long as + present",false1:"As long as + past",false2:"As long as + future"},
{num:350,que:"¿Qué palabra es un conector de contraste suave?",true:"while",false1:"although",false2:"despite"},
{num:351,que:"¿Cuál es la forma correcta del plural de 'index'?",true:"indices",false1:"indexes",false2:"index"},
{num:352,que:"¿Qué preposición se usa con 'prevail'?",true:"upon",false1:"on",false2:"at"},
{num:353,que:"¿Cómo se forma el pasado de 'equip'?",true:"equipped",false1:"equiped",false2:"equipping"},
{num:354,que:"¿Qué significa 'pass out'?",true:"Desmayarse",false1:"Pasar fuera",false2:"Repartir"},
{num:355,que:"¿Cuál es la forma interrogativa de 'He dare not speak'?",true:"Dare he not speak?",false1:"Does he dare not speak?",false2:"Is he dare not speak?"},
{num:356,que:"¿Qué tiempo se usa después de 'after'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:357,que:"¿Cómo se dice 'tan honesto como'?",true:"as honest as",false1:"so honest as",false2:"more honest than"},
{num:358,que:"¿Qué verbo modal expresa falta de obligación?",true:"needn't",false1:"mustn't",false2:"can't"},
{num:359,que:"¿Cuál es la pregunta para 'We used to play'?",true:"Did we use to play?",false1:"Used we to play?",false2:"Do we used to play?"},
{num:360,que:"¿Qué pronombre corresponde a 'anyone'?",true:"they",false1:"he",false2:"it"},
{num:361,que:"¿Cómo se forma el reported speech de 'I need to leave'?",true:"He said he needed to leave",false1:"He said he needs to leave",false2:"He said he need to leave"},
{num:362,que:"¿Qué significa 'drop out'?",true:"Abandonar",false1:"Caerse fuera",false2:"Dejar caer"},
{num:363,que:"¿Cuál es el participio pasado de 'thrive'?",true:"thriven",false1:"throve",false2:"thrived"},
{num:364,que:"¿Qué se usa con 'there will be'?",true:"any noun",false1:"only singular",false2:"only plural"},
{num:365,que:"¿Cómo se dice 'más fuerte que'?",true:"stronger than",false1:"more strong than",false2:"strongest than"},
{num:366,que:"¿Qué preposición se usa con 'conform'?",true:"to",false1:"with",false2:"for"},
{num:367,que:"¿Cuál es la forma correcta: 'The government _____ decided'?",true:"has",false1:"have",false2:"had"},
{num:368,que:"¿Qué significa 'call on'?",true:"Visitar",false1:"Llamar encima",false2:"Pedir"},
{num:369,que:"¿Cómo se forma el futuro con 'be likely to'?",true:"am/is/are likely to + verb",false1:"will likely to + verb",false2:"going to likely to + verb"},
{num:370,que:"¿Qué palabra es un conector de razón?",true:"since",false1:"but",false2:"and"},
{num:371,que:"¿Cuál es la forma correcta del plural de 'appendix'?",true:"appendices",false1:"appendixes",false2:"appendiceses"},
{num:372,que:"¿Qué preposición se usa con 'insure'?",true:"against",false1:"for",false2:"with"},
{num:373,que:"¿Cómo se forma el pasado de 'worship'?",true:"worshipped",false1:"worshiped",false2:"worshipping"},
{num:374,que:"¿Qué significa 'break off'?",true:"Romper relaciones",false1:"Romper fuera",false2:"Interrumpir"},
{num:375,que:"¿Cuál es la forma negativa de 'You need come'?",true:"You need not come",false1:"You don't need come",false2:"You need not to come"},
{num:376,que:"¿Qué tiempo se usa después de 'when'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:377,que:"¿Cómo se dice 'menos peligroso que'?",true:"less dangerous than",false1:"least dangerous than",false2:"fewer dangerous than"},
{num:378,que:"¿Qué verbo modal expresa permiso formal?",true:"may",false1:"can",false2:"could"},
{num:379,que:"¿Cuál es la pregunta para 'She used to dance'?",true:"Did she use to dance?",false1:"Used she to dance?",false2:"Does she used to dance?"},
{num:380,que:"¿Qué pronombre corresponde a 'no one'?",true:"they",false1:"he",false2:"it"},
{num:381,que:"¿Cómo se forma el reported speech de 'I ought to help'?",true:"He said he ought to help",false1:"He said he should help",false2:"He said he must help"},
{num:382,que:"¿Qué significa 'hold back'?",true:"Contener",false1:"Sostener atrás",false2:"Retener"},
{num:383,que:"¿Cuál es el participio pasado de 'slay'?",true:"slain",false1:"slew",false2:"slayed"},
{num:384,que:"¿Qué se usa con 'there can be'?",true:"any noun",false1:"only singular",false2:"only plural"},
{num:385,que:"¿Cómo se dice 'el más valiente'?",true:"the bravest",false1:"the braver",false2:"the most brave"},
{num:386,que:"¿Qué preposición se usa con 'assure'?",true:"of",false1:"for",false2:"with"},
{num:387,que:"¿Cuál es la forma correcta: 'The jury _____ divided'?",true:"is",false1:"are",false2:"be"},
{num:388,que:"¿Qué significa 'put aside'?",true:"Ahorrar",false1:"Poner a un lado",false2:"Guardar"},
{num:389,que:"¿Cómo se forma el condicional con 'in case'?",true:"In case + present",false1:"In case + past",false2:"In case + future"},
{num:390,que:"¿Qué palabra es un conector de elección?",true:"either...or",false1:"both...and",false2:"not only...but also"},
{num:391,que:"¿Cuál es la forma correcta del plural de 'criterion'?",true:"criteria",false1:"criterions",false2:"criterias"},
{num:392,que:"¿Qué preposición se usa con 'commiserate'?",true:"with",false1:"for",false2:"on"},
{num:393,que:"¿Cómo se forma el pasado de 'kidnap'?",true:"kidnapped",false1:"kidnaped",false2:"kidnaping"},
{num:394,que:"¿Qué significa 'stand out'?",true:"Destacar",false1:"Ponerse de pie",false2:"Sobresalir"},
{num:395,que:"¿Cuál es la forma interrogativa de 'They needn't worry'?",true:"Need they worry?",false1:"Do they need worry?",false2:"Are they need worry?"},
{num:396,que:"¿Qué tiempo se usa después de 'once'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:397,que:"¿Cómo se dice 'tan amable como'?",true:"as kind as",false1:"so kind as",false2:"more kind than"},
{num:398,que:"¿Qué verbo modal expresa posibilidad futura?",true:"may",false1:"must",false2:"should"},
{num:399,que:"¿Cuál es la pregunta para 'He had to leave'?",true:"Did he have to leave?",false1:"Had he to leave?",false2:"Has he to leave?"},
{num:400,que:"¿Qué pronombre corresponde a 'somebody'?",true:"they",false1:"he",false2:"it"},
{num:401,que:"¿Cómo se forma el reported speech de 'I used to play'?",true:"He said he used to play",false1:"He said he uses to play",false2:"He said he use to play"},
{num:402,que:"¿Qué significa 'bring up'?",true:"Mencionar",false1:"Criar",false2:"Educar"},
{num:403,que:"¿Cuál es el participio pasado de 'forsake'?",true:"forsaken",false1:"forsook",false2:"forsaked"},
{num:404,que:"¿Qué se usa con 'there might be'?",true:"any noun",false1:"only singular",false2:"only plural"},
{num:405,que:"¿Cómo se dice 'más débil que'?",true:"weaker than",false1:"more weak than",false2:"weakest than"},
{num:406,que:"¿Qué preposición se usa con 'hinder'?",true:"from",false1:"of",false2:"with"},
{num:407,que:"¿Cuál es la forma correcta: 'The family _____ eating'?",true:"is",false1:"are",false2:"be"},
{num:408,que:"¿Qué significa 'take up'?",true:"Comenzar un hobby",false1:"Tomar arriba",false2:"Ocupar espacio"},
{num:409,que:"¿Cómo se forma el futuro con 'be bound to'?",true:"am/is/are bound to + verb",false1:"will bound to + verb",false2:"going to bound to + verb"},
{num:410,que:"¿Qué palabra es un conector de similitud?",true:"similarly",false1:"however",false2:"therefore"},
{num:411,que:"¿Cuál es la forma correcta del plural de 'datum'?",true:"data",false1:"datums",false2:"datas"},
{num:412,que:"¿Qué preposición se usa con 'absolve'?",true:"from",false1:"of",false2:"with"},
{num:413,que:"¿Cómo se forma el pasado de 'program'?",true:"programmed",false1:"programed",false2:"programing"},
{num:414,que:"¿Qué significa 'work out'?",true:"Resolver",false1:"Trabajar fuera",false2:"Ejercitarse"},
{num:415,que:"¿Cuál es la forma negativa de 'I dare say'?",true:"I dare not say",false1:"I don't dare say",false2:"I dare not to say"},
{num:416,que:"¿Qué tiempo se usa después de 'whenever'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:417,que:"¿Cómo se dice 'menos inteligente que'?",true:"less intelligent than",false1:"least intelligent than",false2:"fewer intelligent than"},
{num:418,que:"¿Qué verbo modal expresa capacidad futura?",true:"will be able to",false1:"can",false2:"could"},
{num:419,que:"¿Cuál es la pregunta para 'You ought to know'?",true:"Ought you to know?",false1:"Do you ought to know?",false2:"Are you ought to know?"},
{num:420,que:"¿Qué pronombre corresponde a 'everyone' en formal?",true:"he or she",false1:"they",false2:"it"},
{num:421,que:"¿Cómo se forma el reported speech de 'I would have come'?",true:"He said he would have come",false1:"He said he will have come",false2:"He said he would come"},
{num:422,que:"¿Qué significa 'set out'?",true:"Emprender",false1:"Establecer",false2:"Exponer"},
{num:423,que:"¿Cuál es el participio pasado de 'stride'?",true:"stridden",false1:"strode",false2:"strided"},
{num:424,que:"¿Qué se usa con 'there should be'?",true:"any noun",false1:"only singular",false2:"only plural"},
{num:425,que:"¿Cómo se dice 'el más generoso'?",true:"the most generous",false1:"the generousest",false2:"the more generous"},
{num:426,que:"¿Qué preposición se usa con 'acquit'?",true:"of",false1:"from",false2:"with"},
{num:427,que:"¿Cuál es la forma correcta: 'The audience _____ applauding'?",true:"is",false1:"are",false2:"be"},
{num:428,que:"¿Qué significa 'give back'?",true:"Devolver",false1:"Dar espalda",false2:"Rendir"},
{num:429,que:"¿Cómo se forma el condicional con 'on condition that'?",true:"On condition that + present",false1:"On condition that + past",false2:"On condition that + future"},
{num:430,que:"¿Qué palabra es un conector de énfasis?",true:"indeed",false1:"however",false2:"furthermore"},
{num:431,que:"¿Cuál es la forma correcta del plural de 'medium'?",true:"media",false1:"mediums",false2:"mediams"},
{num:432,que:"¿Qué preposición se usa con 'adhere'?",true:"to",false1:"with",false2:"for"},
{num:433,que:"¿Cómo se forma el pasado de 'refer'?",true:"referred",false1:"refered",false2:"referring"},
{num:434,que:"¿Qué significa 'pass up'?",true:"Rechazar",false1:"Pasar arriba",false2:"Ignorar"},
{num:435,que:"¿Cuál es la forma interrogativa de 'We dare not move'?",true:"Dare we not move?",false1:"Do we dare not move?",false2:"Are we dare not move?"},
{num:436,que:"¿Qué tiempo se usa después de 'till'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:437,que:"¿Cómo se dice 'tan paciente como'?",true:"as patient as",false1:"so patient as",false2:"more patient than"},
{num:438,que:"¿Qué verbo modal expresa posibilidad presente?",true:"may",false1:"must",false2:"should"},
{num:439,que:"¿Cuál es la pregunta para 'They need to study'?",true:"Do they need to study?",false1:"Need they study?",false2:"Are they need study?"},
{num:440,que:"¿Qué pronombre corresponde a 'nobody' en formal?",true:"he or she",false1:"they",false2:"it"},
{num:441,que:"¿Cómo se forma el reported speech de 'I could swim'?",true:"He said he could swim",false1:"He said he can swim",false2:"He said he can swam"},
{num:442,que:"¿Qué significa 'carry out'?",true:"Llevar a cabo",false1:"Llevar fuera",false2:"Realizar"},
{num:443,que:"¿Cuál es el participio pasado de 'undertake'?",true:"undertaken",false1:"undertook",false2:"undertaked"},
{num:444,que:"¿Qué se usa con 'there must be'?",true:"any noun",false1:"only singular",false2:"only plural"},
{num:445,que:"¿Cómo se dice 'más sabio que'?",true:"wiser than",false1:"more wise than",false2:"wisest than"},
{num:446,que:"¿Qué preposición se usa con 'despair'?",true:"of",false1:"for",false2:"with"},
{num:447,que:"¿Cuál es la forma correcta: 'The company _____ expanding'?",true:"is",false1:"are",false2:"be"},
{num:448,que:"¿Qué significa 'put through'?",true:"Poner en contacto",false1:"Poner a través",false2:"Completar"},
{num:449,que:"¿Cómo se forma el futuro con 'be due to'?",true:"am/is/are due to + verb",false1:"will due to + verb",false2:"going to due to + verb"},
{num:450,que:"¿Qué palabra es un conector de finalidad?",true:"so that",false1:"because",false2:"although"},
{num:451,que:"¿Cuál es la forma correcta del plural de 'nucleus'?",true:"nuclei",false1:"nucleuses",false2:"nucleos"},
{num:452,que:"¿Qué preposición se usa con 'coincide'?",true:"with",false1:"to",false2:"for"},
{num:453,que:"¿Cómo se forma el pasado de 'transmit'?",true:"transmitted",false1:"transmited",false2:"transmitting"},
{num:454,que:"¿Qué significa 'turn over'?",true:"Entregar",false1:"Girar",false2:"Voltear"},
{num:455,que:"¿Cuál es la forma negativa de 'You need help'?",true:"You don't need help",false1:"You need not help",false2:"You need no help"},
{num:456,que:"¿Qué tiempo se usa después de 'as long as'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:457,que:"¿Cómo se dice 'menos confiable que'?",true:"less reliable than",false1:"least reliable than",false2:"fewer reliable than"},
{num:458,que:"¿Qué verbo modal expresa deducción presente?",true:"must",false1:"should",false2:"could"},
{num:459,que:"¿Cuál es la pregunta para 'She had better leave'?",true:"Had she better leave?",false1:"Does she better leave?",false2:"Has she better leave?"},
{num:460,que:"¿Qué pronombre corresponde a 'anyone' en formal?",true:"he or she",false1:"they",false2:"it"},
{num:461,que:"¿Cómo se forma el reported speech de 'I might have gone'?",true:"He said he might have gone",false1:"He said he may have gone",false2:"He said he can have gone"},
{num:462,que:"¿Qué significa 'bring forward'?",true:"Adelantar",false1:"Traer adelante",false2:"Proponer"},
{num:463,que:"¿Cuál es el participio pasado de 'withdraw'?",true:"withdrawn",false1:"withdrew",false2:"withdrawed"},
{num:464,que:"¿Qué se usa con 'there ought to be'?",true:"any noun",false1:"only singular",false2:"only plural"},
{num:465,que:"¿Cómo se dice 'el más confiable'?",true:"the most reliable",false1:"the reliableest",false2:"the more reliable"},
{num:466,que:"¿Qué preposición se usa con 'persist'?",true:"in",false1:"on",false2:"at"},
{num:467,que:"¿Cuál es la forma correcta: 'The group _____ singing'?",true:"is",false1:"are",false2:"be"},
{num:468,que:"¿Qué significa 'take after'?",true:"Parecerse a",false1:"Tomar después",false2:"Seguir"},
{num:469,que:"¿Cómo se forma el condicional con 'supposing'?",true:"Supposing + past",false1:"Supposing + present",false2:"Supposing + future"},
{num:470,que:"¿Qué palabra es un conector de lugar?",true:"where",false1:"when",false2:"why"},
{num:471,que:"¿Cuál es la forma correcta del plural de 'fungus'?",true:"fungi",false1:"funguses",false2:"fungos"},
{num:472,que:"¿Qué preposición se usa con 'resort'?",true:"to",false1:"for",false2:"with"},
{num:473,que:"¿Cómo se forma el pasado de 'occur'?",true:"occurred",false1:"occured",false2:"occurring"},
{num:474,que:"¿Qué significa 'call in'?",true:"Llamar para consultar",false1:"Llamar dentro",false2:"Visitar"},
{num:475,que:"¿Cuál es la forma interrogativa de 'He need not wait'?",true:"Need he wait?",false1:"Does he need wait?",false2:"Is he need wait?"},
{num:476,que:"¿Qué tiempo se usa después de 'provided'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:477,que:"¿Cómo se dice 'tan confiable como'?",true:"as reliable as",false1:"so reliable as",false2:"more reliable than"},
{num:478,que:"¿Qué verbo modal expresa deducción pasada?",true:"must have",false1:"should have",false2:"could have"},
{num:479,que:"¿Cuál es la pregunta para 'We ought to help'?",true:"Ought we to help?",false1:"Do we ought to help?",false2:"Are we ought to help?"},
{num:480,que:"¿Qué pronombre corresponde a 'somebody' en formal?",true:"he or she",false1:"they",false2:"it"},
{num:481,que:"¿Cómo se forma el reported speech de 'I should have come'?",true:"He said he should have come",false1:"He said he shall have come",false2:"He said he should come"},
{num:482,que:"¿Qué significa 'hold off'?",true:"Posponer",false1:"Mantener alejado",false2:"Esperar"},
{num:483,que:"¿Cuál es el participio pasado de 'withstand'?",true:"withstood",false1:"withstanded",false2:"withstood"},
{num:484,que:"¿Qué se usa con 'there may be'?",true:"any noun",false1:"only singular",false2:"only plural"},
{num:485,que:"¿Cómo se dice 'más eficiente que'?",true:"more efficient than",false1:"efficienter than",false2:"efficientest than"},
{num:486,que:"¿Qué preposición se usa con 'abound'?",true:"in",false1:"with",false2:"for"},
{num:487,que:"¿Cuál es la forma correcta: 'The class _____ studying'?",true:"is",false1:"are",false2:"be"},
{num:488,que:"¿Qué significa 'put off'?",true:"Posponer",false1:"Apagar",false2:"Desanimar"},
{num:489,que:"¿Cómo se forma el futuro con 'be set to'?",true:"am/is/are set to + verb",false1:"will set to + verb",false2:"going to set to + verb"},
{num:490,que:"¿Qué palabra es un conector de modo?",true:"as if",false1:"because",false2:"although"},
{num:491,que:"¿Cuál es la forma correcta del plural de 'stimulus'?",true:"stimuli",false1:"stimuluses",false2:"stimulos"},
{num:492,que:"¿Qué preposición se usa con 'concur'?",true:"with",false1:"to",false2:"for"},
{num:493,que:"¿Cómo se forma el pasado de 'regret'?",true:"regretted",false1:"regreted",false2:"regretting"},
{num:494,que:"¿Qué significa 'pass on'?",true:"Transmitir",false1:"Pasar adelante",false2:"Fallecer"},
{num:495,que:"¿Cuál es la forma negativa de 'They dare ask'?",true:"They dare not ask",false1:"They don't dare ask",false2:"They dare not to ask"},
{num:496,que:"¿Qué tiempo se usa después de 'in case'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:497,que:"¿Cómo se dice 'menos eficiente que'?",true:"less efficient than",false1:"least efficient than",false2:"fewer efficient than"},
{num:498,que:"¿Qué verbo modal expresa arrepentimiento pasado?",true:"should have",false1:"could have",false2:"must have"},
{num:499,que:"¿Cuál es la pregunta para 'You used to live here'?",true:"Did you use to live here?",false1:"Used you to live here?",false2:"Do you used to live here?"},
{num:500,que:"¿Qué pronombre corresponde a 'everybody' en formal?",true:"he or she",false1:"they",false2:"it"},
   {num:501,que:"¿Cuál es la forma correcta del plural de 'radius'?",true:"radii",false1:"radiuses",false2:"radius"},
{num:502,que:"¿Qué preposición se usa con 'prohibit'?",true:"from",false1:"to",false2:"for"},
{num:503,que:"¿Cómo se forma el pasado de 'benefit'?",true:"benefited",false1:"benefitted",false2:"benefiting"},
{num:504,que:"¿Qué significa 'come about'?",true:"Suceder",false1:"Venir alrededor",false2:"Aparecer"},
{num:505,que:"¿Cuál es la forma negativa de 'I used to work'?",true:"I didn't use to work",false1:"I used not to work",false2:"I don't used to work"},
{num:506,que:"¿Qué tiempo se usa después de 'by the time' en futuro?",true:"Present simple",false1:"Future perfect",false2:"Past simple"},
{num:507,que:"¿Cómo se dice 'más flexible que'?",true:"more flexible than",false1:"flexibler than",false2:"flexiblest than"},
{num:508,que:"¿Qué verbo modal expresa posibilidad en presente?",true:"may",false1:"must",false2:"should"},
{num:509,que:"¿Cuál es la pregunta para 'He need not come'?",true:"Need he come?",false1:"Does he need come?",false2:"Is he need come?"},
{num:510,que:"¿Qué pronombre corresponde a 'everything'?",true:"it",false1:"they",false2:"them"},
{num:511,que:"¿Cómo se forma el reported speech de 'I must have left'?",true:"He said he must have left",false1:"He said he had to have left",false2:"He said he must left"},
{num:512,que:"¿Qué significa 'do up'?",true:"Abrochar",false1:"Hacer arriba",false2:"Renovar"},
{num:513,que:"¿Cuál es el participio pasado de 'bid'?",true:"bidden",false1:"bid",false2:"bade"},
{num:514,que:"¿Qué se usa con 'there appears to be'?",true:"singular noun",false1:"plural noun",false2:"uncountable noun"},
{num:515,que:"¿Cómo se dice 'el más flexible'?",true:"the most flexible",false1:"the flexibleest",false2:"the more flexible"},
{num:516,que:"¿Qué preposición se usa con 'protest'?",true:"against",false1:"about",false2:"for"},
{num:517,que:"¿Cuál es la forma correcta: 'The series _____ interesting'?",true:"is",false1:"are",false2:"be"},
{num:518,que:"¿Qué significa 'fall through'?",true:"Quedar en nada",false1:"Caer a través",false2:"Fracasar"},
{num:519,que:"¿Cómo se forma el condicional con 'even if'?",true:"Even if + present",false1:"Even if + past",false2:"Even if + future"},
{num:520,que:"¿Qué palabra es un conector de condición negativa?",true:"unless",false1:"if",false2:"whether"},
{num:521,que:"¿Cuál es la forma correcta del plural de 'syllabus'?",true:"syllabi",false1:"syllabuses",false2:"syllabus"},
{num:522,que:"¿Qué preposición se usa con 'reconcile'?",true:"with",false1:"to",false2:"for"},
{num:523,que:"¿Cómo se forma el pasado de 'focus'?",true:"focused",false1:"focussed",false2:"focusing"},
{num:524,que:"¿Qué significa 'get by'?",true:"Arreglárselas",false1:"Pasar por",false2:"Conseguir"},
{num:525,que:"¿Cuál es la forma interrogativa de 'You'd better not go'?",true:"Had you better not go?",false1:"Would you better not go?",false2:"Do you better not go?"},
{num:526,que:"¿Qué tiempo se usa después de 'the moment'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:527,que:"¿Cómo se dice 'tan flexible como'?",true:"as flexible as",false1:"so flexible as",false2:"more flexible than"},
{num:528,que:"¿Qué verbo modal expresa consejo pasado?",true:"should have",false1:"could have",false2:"must have"},
{num:529,que:"¿Cuál es la pregunta para 'We need to leave'?",true:"Do we need to leave?",false1:"Need we leave?",false2:"Are we need leave?"},
{num:530,que:"¿Qué pronombre corresponde a 'nothing'?",true:"it",false1:"they",false2:"them"},
{num:531,que:"¿Cómo se forma el reported speech de 'I can have finished'?",true:"He said he could have finished",false1:"He said he can have finished",false2:"He said he could finish"},
{num:532,que:"¿Qué significa 'make out'?",true:"Distinguir",false1:"Hacer fuera",false2:"Comprender"},
{num:533,que:"¿Cuál es el participio pasado de 'cleave'?",true:"cleft",false1:"clove",false2:"cleaved"},
{num:534,que:"¿Qué se usa con 'there seems to be'?",true:"singular noun",false1:"plural noun",false2:"uncountable noun"},
{num:535,que:"¿Cómo se dice 'menos flexible que'?",true:"less flexible than",false1:"least flexible than",false2:"fewer flexible than"},
{num:536,que:"¿Qué preposición se usa con 'dispose'?",true:"of",false1:"from",false2:"with"},
{num:537,que:"¿Cuál es la forma correcta: 'The species _____ endangered'?",true:"is",false1:"are",false2:"be"},
{num:538,que:"¿Qué significa 'pass for'?",true:"Pasar por",false1:"Pasar para",false2:"Aprobar"},
{num:539,que:"¿Cómo se forma el futuro con 'be sure to'?",true:"am/is/are sure to + verb",false1:"will sure to + verb",false2:"going to sure to + verb"},
{num:540,que:"¿Qué palabra es un conector de explicación?",true:"that is",false1:"however",false2:"therefore"},
{num:541,que:"¿Cuál es la forma correcta del plural de 'focus'?",true:"foci",false1:"focuses",false2:"focus"},
{num:542,que:"¿Qué preposición se usa con 'hint'?",true:"at",false1:"to",false2:"for"},
{num:543,que:"¿Cómo se forma el pasado de 'bias'?",true:"biased",false1:"biassed",false2:"biasing"},
{num:544,que:"¿Qué significa 'lay down'?",true:"Establecer",false1:"Acostarse",false2:"Rendir"},
{num:545,que:"¿Cuál es la forma negativa de 'They dare speak'?",true:"They dare not speak",false1:"They don't dare speak",false2:"They dare not to speak"},
{num:546,que:"¿Qué tiempo se usa después de 'directly'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:547,que:"¿Cómo se dice 'más creativo que'?",true:"more creative than",false1:"creativer than",false2:"creativest than"},
{num:548,que:"¿Qué verbo modal expresa permiso en pasado?",true:"could",false1:"might",false2:"was allowed to"},
{num:549,que:"¿Cuál es la pregunta para 'She had to work'?",true:"Did she have to work?",false1:"Had she to work?",false2:"Has she to work?"},
{num:550,que:"¿Qué pronombre corresponde a 'something'?",true:"it",false1:"they",false2:"them"},
{num:551,que:"¿Cómo se forma el reported speech de 'I will have finished'?",true:"He said he would have finished",false1:"He said he will have finished",false2:"He said he would finish"},
{num:552,que:"¿Qué significa 'set about'?",true:"Empezar",false1:"Establecer acerca",false2:"Atacar"},
{num:553,que:"¿Cuál es el participio pasado de 'bereave'?",true:"bereft",false1:"bereaved",false2:"bereaven"},
{num:554,que:"¿Qué se usa con 'there tends to be'?",true:"singular noun",false1:"plural noun",false2:"uncountable noun"},
{num:555,que:"¿Cómo se dice 'el más creativo'?",true:"the most creative",false1:"the creativeest",false2:"the more creative"},
{num:556,que:"¿Qué preposición se usa con 'meddle'?",true:"in",false1:"with",false2:"on"},
{num:557,que:"¿Cuál es la forma correcta: 'The means _____ available'?",true:"is",false1:"are",false2:"be"},
{num:558,que:"¿Qué significa 'put across'?",true:"Comunicar",false1:"Poner a través",false2:"Transmitir"},
{num:559,que:"¿Cómo se forma el condicional con 'whether or not'?",true:"Whether or not + present",false1:"Whether or not + past",false2:"Whether or not + future"},
{num:560,que:"¿Qué palabra es un conector de alternativa?",true:"or",false1:"and",false2:"but"},
{num:561,que:"¿Cuál es la forma correcta del plural of 'alumnus'?",true:"alumni",false1:"alumnuses",false2:"alumnus"},
{num:562,que:"¿Qué preposición se usa con 'partake'?",true:"in",false1:"of",false2:"with"},
{num:563,que:"¿Cómo se forma el pasado de 'counsel'?",true:"counselled",false1:"counseled",false2:"counselling"},
{num:564,que:"¿Qué significa 'take to'?",true:"Tomarle gusto a",false1:"Llevar a",false2:"Escapar"},
{num:565,que:"¿Cuál es la forma interrogativa de 'We need not worry'?",true:"Need we worry?",false1:"Do we need worry?",false2:"Are we need worry?"},
{num:566,que:"¿Qué tiempo se usa después de 'immediately'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:567,que:"¿Cómo se dice 'tan creativo como'?",true:"as creative as",false1:"so creative as",false2:"more creative than"},
{num:568,que:"¿Qué verbo modal expresa posibilidad remota en pasado?",true:"might have",false1:"could have",false2:"should have"},
{num:569,que:"¿Cuál es la pregunta para 'They ought to know'?",true:"Ought they to know?",false1:"Do they ought to know?",false2:"Are they ought to know?"},
{num:570,que:"¿Qué pronombre corresponde a 'anything'?",true:"it",false1:"they",false2:"them"},
{num:571,que:"¿Cómo se forma el reported speech de 'I may have been'?",true:"He said he might have been",false1:"He said he may have been",false2:"He said he can have been"},
{num:572,que:"¿Qué significa 'bring round'?",true:"Hacer volver en sí",false1:"Traer alrededor",false2:"Convencer"},
{num:573,que:"¿Cuál es el participio pasado de 'smite'?",true:"smitten",false1:"smote",false2:"smited"},
{num:574,que:"¿Qué se usa con 'there happens to be'?",true:"singular noun",false1:"plural noun",false2:"uncountable noun"},
{num:575,que:"¿Cómo se dice 'menos creativo que'?",true:"less creative than",false1:"least creative than",false2:"fewer creative than"},
{num:576,que:"¿Qué preposición se usa con 'preside'?",true:"over",false1:"at",false2:"in"},
{num:577,que:"¿Cuál es la forma correcta: 'The economics _____ complex'?",true:"is",false1:"are",false2:"be"},
{num:578,que:"¿Qué significa 'hold over'?",true:"Posponer",false1:"Sostener sobre",false2:"Mantener"},
{num:579,que:"¿Cómo se forma el futuro con 'be certain to'?",true:"am/is/are certain to + verb",false1:"will certain to + verb",false2:"going to certain to + verb"},
{num:580,que:"¿Qué palabra es un conector de comparación?",true:"likewise",false1:"however",false2:"therefore"},
{num:581,que:"¿Cuál es la forma correcta del plural de 'vertebra'?",true:"vertebrae",false1:"vertebras",false2:"vertebra"},
{num:582,que:"¿Qué preposición se usa con 'tamper'?",true:"with",false1:"on",false2:"at"},
{num:583,que:"¿Cómo se forma el pasado de 'model'?",true:"modelled",false1:"modeled",false2:"modelling"},
{num:584,que:"¿Qué significa 'make up for'?",true:"Compensar",false1:"Inventar para",false2:"Maquillarse"},
{num:585,que:"¿Cuál es la forma negativa de 'You dare ask'?",true:"You dare not ask",false1:"You don't dare ask",false2:"You dare not to ask"},
{num:586,que:"¿Qué tiempo se usa después de 'the minute'?",true:"Present simple",false1:"Future simple",false2:"Past simple"},
{num:587,que:"¿Cómo se dice 'más organizado que'?",true:"more organized than",false1:"organizeder than",false2:"organizedest than"},
{num:588,que:"¿Qué verbo modal expresa expectativa en pasado?",true:"should have",false1:"could have",false2:"must have"},
{num:589,que:"¿Cuál es la pregunta para 'He used to teach'?",true:"Did he use to teach?",false1:"Used he to teach?",false2:"Does he used to teach?"},
{num:590,que:"¿Qué pronombre corresponde a 'everywhere'?",true:"it",false1:"they",false2:"them"},
{num:591,que:"¿Cómo se forma el reported speech de 'I shall have been'?",true:"He said he would have been",false1:"He said he should have been",false2:"He said he shall have been"},
{num:592,que:"¿Qué significa 'die out'?",true:"Extinguirse",false1:"Morir fuera",false2:"Desaparecer"},
{num:593,que:"¿Cuál es el participio pasado de 'sting'?",true:"stung",false1:"stang",false2:"stinged"},
{num:594,que:"¿Qué se usa con 'there is likely to be'?",true:"singular noun",false1:"plural noun",false2:"uncountable noun"},
{num:595,que:"¿Cómo se dice 'el más organizado'?",true:"the most organized",false1:"the organizedest",false2:"the more organized"},
{num:596,que:"¿Qué preposición se usa con 'rejoice'?",true:"at",false1:"in",false2:"for"},
{num:597,que:"¿Cuál es la forma correcta: 'The politics _____ complicated'?",true:"is",false1:"are",false2:"be"},
{num:598,que:"¿Qué significa 'put down to'?",true:"Atribuir",false1:"Poner abajo a",false2:"Registrar"},
{num:599,que:"¿Cómo se forma el condicional con 'in the event that'?",true:"In the event that + present",false1:"In the event that + past",false2:"In the event that + future"},
{num:600,que:"¿Qué palabra es un conector de consecuencia inmediata?",true:"thus",false1:"however",false2:"moreover"}
];
/* 

*/

let currentQuestionIndex = 0;

document.addEventListener('DOMContentLoaded', function() {
    setQ(currentQuestionIndex);
    setupEventListeners();
});

shuffleArray(qna);

function setQ(index) {
    const currentQ = qna[index];
    document.getElementById("question").innerHTML = currentQ.que;
    
    const answers = [currentQ.true, currentQ.false1, currentQ.false2];
    shuffleArray(answers);
    
    document.getElementById("button1").innerHTML = answers[0];
    document.getElementById("button2").innerHTML = answers[1];
    document.getElementById("button3").innerHTML = answers[2];
    
    // Store correct answer for checking
    document.getElementById("button1").dataset.correct = answers[0] === currentQ.true;
    document.getElementById("button2").dataset.correct = answers[1] === currentQ.true;
    document.getElementById("button3").dataset.correct = answers[2] === currentQ.true;
}

function setupEventListeners() {
    document.getElementById("button1").addEventListener("click", function() {
        checkAnswer(this);
    });
    document.getElementById("button2").addEventListener("click", function() {
        checkAnswer(this);
    });
    document.getElementById("button3").addEventListener("click", function() {
        checkAnswer(this);
    });
}

function checkAnswer(button) {
    const isCorrect = button.dataset.correct === "true";
    const buttonbox = document.getElementById("workbox");

    if (isCorrect) {
        workbox.style.backgroundColor = "green";
        // Move to next question after delay
        setTimeout(function() {
            currentQuestionIndex++;
            if (currentQuestionIndex < qna.length) {
                setQ(currentQuestionIndex);
                buttonbox.style.backgroundColor = ""; // Reset color
            } else {
                document.getElementById("question").innerHTML = "Quiz Complete! 🎉";
                buttonbox.innerHTML = "<p>Yo amo tu <3</p>";
            }
        }, 1000); // Added missing delay parameter
    } else {
        buttonbox.style.backgroundColor = "red";
        // Reset color after short delay
        setTimeout(function() {
            buttonbox.style.backgroundColor = "";
        }, 1000);
    }
}

// Helper function to shuffle array (Fisher-Yates algorithm)
function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;


}

